org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
forge_version=47.4.0
loader_version_range=[46,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=cinchsabandonedhouses
mod_name=Cinch's Abandoned Houses
mod_license=MIT
mod_version=2.0.1
mod_group_id=net.cinchtail.cinchsabandonedhouses
mod_authors=Cinchtail
mod_description=Abandoned house structures that randomly generate around the world.